KEY_F1	1	             /usr/bin/hassio-keypress-send "KEY_F1-1"
KEY_F1	0	             /usr/bin/hassio-keypress-send "KEY_F1-0"
KEY_F2	1	             /usr/bin/hassio-keypress-send "KEY_F2-1"
KEY_F2	0	             /usr/bin/hassio-keypress-send "KEY_F2-0"
KEY_F3	1	             /usr/bin/hassio-keypress-send "KEY_F3-1"
KEY_F3	0	             /usr/bin/hassio-keypress-send "KEY_F3-0"
KEY_F4	1	             /usr/bin/hassio-keypress-send "KEY_F4-1"
KEY_F4	0	             /usr/bin/hassio-keypress-send "KEY_F4-0"
KEY_F5	1	             /usr/bin/hassio-keypress-send "KEY_F5-1"
KEY_F5	0	             /usr/bin/hassio-keypress-send "KEY_F5-0"
KEY_F6	1	             /usr/bin/hassio-keypress-send "KEY_F6-1"
KEY_F6	0	             /usr/bin/hassio-keypress-send "KEY_F6-0"
KEY_HOME	1	         /usr/bin/hassio-keypress-send "KEY_HOME-1"
KEY_HOME	0	         /usr/bin/hassio-keypress-send "KEY_HOME-0"
KEY_SLEEP	1	         /usr/bin/hassio-keypress-send "KEY_SLEEP-1"
KEY_SLEEP	0	         /usr/bin/hassio-keypress-send "KEY_SLEEP-0"
KEY_KPPLUS	1	         /usr/bin/hassio-keypress-send "KEY_KPPLUS-1"
KEY_KPPLUS	0	         /usr/bin/hassio-keypress-send "KEY_KPPLUS-0"
KEY_LEFT	1	         /usr/bin/hassio-keypress-send "KEY_LEFT-1"
KEY_LEFT	0	         /usr/bin/hassio-keypress-send "KEY_LEFT-0"
KEY_PREVIOUSSONG	1	 /usr/bin/hassio-keypress-send "KEY_PREVIOUSSONG-1"
KEY_PREVIOUSSONG	0	 /usr/bin/hassio-keypress-send "KEY_PREVIOUSSONG-0"
KEY_PLAYPAUSE	1	     /usr/bin/hassio-keypress-send "KEY_PLAYPAUSE-1"
KEY_PLAYPAUSE	0	     /usr/bin/hassio-keypress-send "KEY_PLAYPAUSE-0"
KEY_NEXTSONG	1	     /usr/bin/hassio-keypress-send "KEY_NEXTSONG-1"
KEY_NEXTSONG	0	     /usr/bin/hassio-keypress-send "KEY_NEXTSONG-0"
KEY_PLAY	1	         /usr/bin/hassio-keypress-send "KEY_PLAY-1"
KEY_PLAY	0	         /usr/bin/hassio-keypress-send "KEY_PLAY-0"
KEY_RIGHT	1	         /usr/bin/hassio-keypress-send "KEY_RIGHT-1"
KEY_RIGHT	0	         /usr/bin/hassio-keypress-send "KEY_RIGHT-0"
REL_WHEEL	1	         /usr/bin/hassio-keypress-send "REL_WHEEL-1"
REL_WHEEL	-1	         /usr/bin/hassio-keypress-send "REL_WHEEL-0"
KEY_MUTE	1	         /usr/bin/hassio-keypress-send "KEY_MUTE-1"
KEY_MUTE	0	         /usr/bin/hassio-keypress-send "KEY_MUTE-0"
REL_MISC	1	         /usr/bin/hassio-keypress-send "REL_MISC-1"
REL_MISC	-1	         /usr/bin/hassio-keypress-send "REL_MISC-0"
KEY_POWER	1	         /usr/bin/hassio-keypress-send "KEY_POWER-1"
KEY_POWER	0	         /usr/bin/hassio-keypress-send "KEY_POWER-0"
