services:
  squeezeos-dev:
    build: .
    image: squeezeos-dev
    user: 1000:1000
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
#      - SQUEEZEOS_SRC_MIRROR=http://127.0.0.1:8730/poky-cache
    volumes:
      - ../poky:/poky

    stdin_open: true # docker run -i
    tty: true        # docker run -t

